docs(README): Improve example of `file` option so it's obvious that it is not relative to `context` option
docker/build-push-action pull request #189
Opened 2020-10-20 17:18 UTC by jtomaszewski

I just spent 30 min debugging "why is buildx not working on my github runner?", just to learn that the `file` option is not relative to the `context` option. (So basically if you want to build'n'push from a different directory, which has the `Dockerfile` and should be the `context`, you need to update both options.)

Especially since the error message that appears then isn't really helpful:

![image](https://user-images.githubusercontent.com/1862580/96621313-c6265880-1308-11eb-8a97-0ade003562db.png)

Changing from

```
          context: ./images/php/${{ env.PHP_VERSION }}/
```

to

```
          context: ./images/php/${{ env.PHP_VERSION }}/
          file: ./images/php/${{ env.PHP_VERSION }}/Dockerfile
```

fixed the problem in my case.

(The error message could be improved as well I guess, but let's say that's another nice-to-have thing.)

2020-10-22 19:58 UTC, crazy-max commented
@jtomaszewski Please sign your commit as explained in https://github.com/docker/build-push-action/pull/186#issuecomment-712984175

2020-10-26 11:01 UTC, jtomaszewski commented
@crazy-max done

2020-10-26 11:25 UTC, crazy-max requested changes
@jtomaszewski 

> just to learn that the file option is not relative to the context option.

That's [the expected behavior](https://docs.docker.com/engine/reference/commandline/build/#extended-description) of the `build` command (with `docker buildx build` or `docker build`):

> The `docker build` command builds Docker images from a Dockerfile and a “context”. A build’s context is the set of files located in the specified `PATH` or `URL`. The build process can refer to any of the files in the context. For example, your build can use a COPY instruction to reference a file in the context.

2020-10-26 11:25 UTC, crazy-max commented on README.md
> +          file: ./images/app/Dockerfile
Not necessary, please revert these changes.

2020-10-26 11:25 UTC, crazy-max commented on README.md
> +| `file`              | String   | Path to the Dockerfile (default `./Dockerfile`) |
LGTM for this one, thanks

2020-11-06 13:22 UTC, jtomaszewski commented on README.md
> +          file: ./images/app/Dockerfile
Maybe... it used to be way different in `v1` ( `path` would apply to both ). Let's say notes in https://github.com/docker/build-push-action/blob/master/UPGRADE.md are enough though.

2020-11-06 13:31 UTC, jtomaszewski commented
Corrected @crazy-max

2020-11-06 13:34 UTC, crazy-max approved these changes
LGTM thanks!

2020-11-06 13:34 UTC, merged