Update documentation on the file argument
docker/build-push-action pull request #244
Opened 2020-12-02 22:38 UTC by liboz

Our team hit this issue today, but with `buildx` the file argument needs to be specified from the root directory not just the relative directory from the `context` (`PATH`) argument .

See:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/13482895/100939863-06aaf180-34c5-11eb-972b-27a83984d6ed.png">

This updates the readme to reflect this fact.

2020-12-03 22:34 UTC, crazy-max commented
@liboz 

> but with buildx the file argument needs to be specified from the root directory not just the relative directory from the context (PATH) argument .

This is the same behavior as `docker build`. See https://github.com/docker/build-push-action/pull/189#pullrequestreview-516680807

2020-12-04 13:48 UTC, liboz commented
@crazy-max You're right and I suppose that was mostly some inexperience on our part. I think updating the documents to reflect the fact that the implicit default path includes the `context` would be a helpful change for everyone involved though.

2020-12-14 08:31 UTC, muru commented
@liboz and @crazy-max Is the default really `{context}/Dockerfile`? That's what `docker build`'s behaviour is, but not the `docker/build-push-action@v2` action's. If I use `context: foo` without a `file` argument, it still looks for the `Dockerfile` in the current working directory. If I specify both `context: foo` and `file: foo/Dockerfile`, OTOH, the action works. Possibly because of [this line](https://github.com/docker/build-push-action/blob/v2.2.1/src/context.ts#L60):
```ts
file: core.getInput('file') || 'Dockerfile',
```
So when specifying the the path context, the file has to be set too. Is that intended? It seems a bit redundant. Maybe that line should be something like (pardon my TypeScript):
```ts
file: core.getInput('file') || [core.getInput('context'), "Dockerfile"].filter(Boolean).join("/"),
```

2020-12-14 14:17 UTC, liboz commented
@muru After doing some more poking around, I think you're right and that suggestion makes sense.

2020-12-14 16:51 UTC, crazy-max commented
@muru @liboz As I said, this is [the expected and same behavior](https://docs.docker.com/engine/reference/commandline/build/#extended-description) for `docker build`, `docker buildx build` and `build-push-action`:

> The `docker build` command builds Docker images from a Dockerfile and a “context”. A build’s context is the set of files located in the specified `PATH` or `URL`. The build process can refer to any of the files in the context. For example, your build can use a COPY instruction to reference a file in the context.

You can test it yourself locally if you want:

Given folder structure and files:

```
project
│   Dockerfile    
│
└───test
│   │   Dockerfile.test
│   │   app.txt
```

```
# ./Dockerfile
FROM alpine
RUN echo "Hello world!"
```

```
# ./test/Dockerfile.test
FROM alpine
RUN echo "Hello world!"
COPY app.txt ./
```

And the following commands and expected result:

```shell
$ docker build .
OK

$ docker build -f Dockerfile.test test
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount199981535/Dockerfile.test: no such file or directory

$ docker build -f ./test/Dockerfile.test ./test
OK

$ docker build -f ./test/Dockerfile.test .
failed to compute cache key: "/app.txt" not found: not found
```

2020-12-14 16:56 UTC, muru commented
@crazy-max that's all fine, I'm not disputing that. What I'm talking of is this case:

```
project   
└───test
│   │   Dockerfile
│   │   app.txt
```
Here, `docker build test` will use `test/Dockerfile` without having to specify it using `-f`. That's not the case with the action, however.

2020-12-14 16:58 UTC, crazy-max commented
@muru 

> Here, docker build test will use test/Dockerfile without having to specify it using -f. That's not the case with the action, however.

Yes if you don't specify a Dockerfile that's right

2020-12-14 17:08 UTC, crazy-max commented
@muru After what we have just said we could replace this line with:

https://github.com/docker/build-push-action/blob/0db984c1826869dcd0740ff26ff75ff543238fd9/src/context.ts#L60

With:

```ts
 file: core.getInput('file'),
```

And remove:

https://github.com/docker/build-push-action/blob/0db984c1826869dcd0740ff26ff75ff543238fd9/action.yml#L19

And rely on default behavior.

2020-12-17 11:10 UTC, crazy-max requested changes
Also update `action.yml`. See my comment https://github.com/docker/build-push-action/pull/244#issuecomment-744579942

2020-12-17 11:10 UTC, crazy-max commented on README.md
> +| `file`              | String   | Path to the Dockerfile. If changed from the default, the full path must be specified from the working directory (default `{context}/Dockerfile`) |
Should be enough with the default behavior now:

```suggestion
| `file`              | String   | Path to the Dockerfile (default `PATH/Dockerfile`) |
```

2020-12-17 11:10 UTC, crazy-max commented on src/context.ts
> +  file?: string;
Keep as required:

```suggestion
  file: string;
```

2020-12-17 11:10 UTC, crazy-max commented on src/context.ts
> +    file: core.getInput('file') || undefined,
```suggestion
    file: core.getInput('file'),
```

2020-12-18 14:05 UTC, liboz commented on README.md
> +| `file`              | String   | Path to the Dockerfile. If changed from the default, the full path must be specified from the working directory (default `{context}/Dockerfile`) |
I think it's still useful to have the default of (
```
default `{context}/Dockerfile`)
```
shown as that is what the command line defaults to.

2020-12-18 14:08 UTC, liboz commented
@crazy-max I tried to fix all the tests. However, when I run it locally I only find/execute 44 tests while in the CI, it seems to be executing 45 tests (with arguments that don't seem to be in the test file at all). Do you have any idea where that test might be coming from?

2020-12-18 14:33 UTC, crazy-max requested changes
@liboz You forgot to remove [this line](https://github.com/docker/build-push-action/blob/181ed59064b7c509e0b1252a36c4d3faa278f6bb/__tests__/context.test.ts#L253)

2020-12-18 14:47 UTC, crazy-max commented
@liboz Can you squash your commits and rebase please?

2020-12-18 15:09 UTC, liboz commented
@crazy-max  Done

2020-12-18 15:45 UTC, crazy-max commented
@liboz About the failed test, you forgot to remove [this line](https://github.com/liboz/build-push-action/blob/d5702a3701e0b03092b64ea03c8e31e47caf9783/__tests__/context.test.ts#L178).

2020-12-18 15:47 UTC, liboz commented
@crazy-max Ah, thanks for pointing that out. It was because I hadn't merged master. Thanks for reviewing 😃

2020-12-18 15:58 UTC, crazy-max approved these changes
PTAL @tonistiigi

2020-12-29 19:17 UTC, tonistiigi approved these changes

2020-12-29 19:17 UTC, merged