clarify pull option
docker/build-push-action pull request #435
Opened 2021-08-16 20:30 UTC by oceanBT

2021-08-16 20:54 UTC, crazy-max commented
Don't think that's necessary. Also it does not only concern `FROM` instructions but also:
* `# syntax=<image>`
* `COPY --from=<image>`
* `RUN --mount=type=bind,from=<image>`

2021-08-18 22:41 UTC, oceanBT commented
It took me 30 minutes to figure out exactly what is intended by "the image". Others seem to have had a similar experience (#55). 

> Also it does not only concern `FROM` instructions but also:
> 
> * `# syntax=<image>`
> * `COPY --from=<image>`
> * `RUN --mount=type=bind,from=<image>`

Thanks for this advice! I have not known that yet.

How about: 

> pull all images that are referenced in the Dockerfile (e. g. `FROM`, `COPY`) during build

2021-09-28 00:39 UTC, crazy-max commented
@oceanBT 

`Always attempt to pull a newer version of all images that are referenced in the Dockerfile` sgtm.

Might need [changes upstream](https://github.com/docker/buildx/blob/c643c2ca954c19f2a73601745e14d69967bef583/commands/build.go#L367) to keep it consistent. PTAL @tonistiigi @thaJeztah

2021-09-28 11:01 UTC, thaJeztah commented
LOL, I started to write a comment, but opened a can of worms while writing it. Anyway; here's what I wrote 😅 


> Always attempt to pull a newer version of all images that are referenced in the Dockerfile

SGTM; perhaps "newer versions"

```
Always attempt to pull newer versions of images that are referenced in the Dockerfile.
```

Unless we want to make it more generic (not mention Dockerfile?)

```
Always attempt to pull newer versions of the images images used by the build.
```


Also looking a bit at "attempt to" (it's a bit ambiguous, as it may mean either "try to pull, but don't error if it fails", or "if a newer image is available, pull it")

```
Always pull newer versions of the images images used by the build.
```

Which brings it to "what is _newer_ ? " (because it will pull the same tag, not "update to a newer version") 🤔

2021-11-16 20:18 UTC, crazy-max requested changes
Check DCO (sign-off is missing)

2021-11-16 20:18 UTC, crazy-max commented on README.md
> +
Revert this change

2021-11-16 21:30 UTC, crazy-max requested changes
And squash your commits, thanks.

2021-11-16 21:30 UTC, crazy-max commented on README.md
> -| `pull`              | Bool     | Always attempt to pull a newer version of the image (default `false`) |
Please add back

```
(default `false`)
```

2022-02-28 04:26 UTC, closed without merging