Added 'quiet' docker arg support
docker/build-push-action pull request #486
Opened 2021-10-15 15:33 UTC by jj-mino

2021-11-02 14:53 UTC, fearphage requested changes
You should try to maintain the current state of things.

2021-11-02 14:53 UTC, fearphage commented on README.md
> +| `quiet`             | String   | Suppress the build output and print image ID on success |
Looks like the previous options were in alphabetical order.

2021-11-02 14:53 UTC, fearphage commented on src/context.ts
> +  quiet: boolean;
Alphabetize here too.

2021-11-02 14:53 UTC, fearphage commented on src/context.ts
> +    quiet: core.getBooleanInput('quiet'),
Alphabetize here too.

2021-11-16 17:18 UTC, crazy-max commented
As discussed in #501, we are not going to add the `quiet` flag as it does not make much sense for the action itself.

2021-11-16 17:18 UTC, closed without merging