chore: update dev dependencies and workflow
docker/build-push-action pull request #571
Opened 2022-03-14 13:41 UTC by crazy-max

prep for #564

* remove hack folder
* cleanup bake def
* cleanup and update dev deps
* remove prettier and switch to eslint
* jest 27
* generate source map and licenses with ncc

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

2022-03-14 15:11 UTC, mark-dr requested changes

2022-03-14 15:11 UTC, mark-dr commented on tsconfig.json
>    ]
This is fine, but you could also consider switching to:

```json
"include": ["./src"]
```

2022-03-14 15:11 UTC, mark-dr commented on package.json
> -    "format-check": "prettier --check **/*.ts",
Why not run Prettier?

2022-03-14 15:11 UTC, mark-dr commented on package.json
> -    "format-check": "prettier --check **/*.ts",
(PS, if you do run Prettier, my recommendation is to do the check step with the prettier eslint plugin)

2022-03-14 15:26 UTC, crazy-max commented on .prettierrc.json
> -}
Oh didn't know about that, thanks!

2022-03-15 11:40 UTC, mark-dr commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
@crazy-max you marked this as resolved, but it looks like it's still an issue in this version of the code?

2022-03-15 12:38 UTC, crazy-max commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
As I missed that one, I will try your suggestion.

2022-03-15 13:01 UTC, crazy-max commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
@mark-dr Doesn't seem to work:

```
 FAIL  __tests__/buildx.test.ts                                                                                                                                                                           
  ● Test suite failed to run
                                                                                                                                                                                                          
    __tests__/buildx.test.ts:140:14 - error TS1308: 'await' expressions are only allowed within async functions and at the top levels of modules.                                                         
                                                                                                                                                                                                          
    140   skipItIf(!(await isDaemonRunning()))(                                                                                                                                                           
                     ~~~~~                                                                                                                                                                                
                                                                                                                                                                                                          
      __tests__/buildx.test.ts:139:24                                                                                                                                                                     
        139 describe('getVersion', () => {
                                   ~~~~~~~
        Did you mean to mark this function as 'async'?
```

And indeed as you said it always returns true with the current impl.

2022-03-15 17:30 UTC, crazy-max commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
Hum I don't think we can return return a promise from describe but I will check that.

2022-03-15 17:43 UTC, mark-dr commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
I found some sample code that suggested you could, but I didn't test it. If not, the easiest solution is probably to move the check into the test itself. [this comment](https://github.com/facebook/jest/issues/7245#issuecomment-791285252) suggests you can mark a test as skipped by executing `pending()` from inside it, might be worth a try.

2022-03-15 21:00 UTC, crazy-max commented on __tests__/buildx.test.ts
> +  skipItIf(!isDaemonRunning())(
Ok afterall this condition was not necessary for this test.

2022-03-21 08:55 UTC, merged