Document the use of scope with GHA caching
docker/build-push-action pull request #709
Opened 2022-10-25 03:46 UTC by yanirs

Resolves #706.

2022-11-01 14:09 UTC, crazy-max commented on docs/advanced/cache.md
> +overwriting the cache index. See https://github.com/moby/buildkit/issues/2885.
Better to link to https://docs.docker.com/build/building/cache/backends/gha/#scope

2022-11-01 14:09 UTC, crazy-max commented on docs/advanced/cache.md
> +overwriting the cache index. See https://github.com/moby/buildkit/issues/2885.
Better to link to https://docs.docker.com/build/building/cache/backends/gha/#scope

2022-11-01 14:10 UTC, crazy-max requested changes

2022-11-01 14:10 UTC, crazy-max commented on docs/advanced/cache.md
> +overwriting the cache index. See https://github.com/moby/buildkit/issues/2885.
Better to link to https://docs.docker.com/build/building/cache/backends/gha/#scope

2022-11-01 23:25 UTC, yanirs commented on docs/advanced/cache.md
> +overwriting the cache index. See https://github.com/moby/buildkit/issues/2885.
Good point. Updated.

2022-11-02 06:22 UTC, crazy-max requested changes
Can you squash your commits please?

2022-11-29 19:58 UTC, yanirs commented
Yeah, I actually do mind. This is a trivial change that'd help people who hit the same issue, but there was no need for it to have multiple review rounds or for it to be sitting as an open PR for a month. Specifically, you could have squashed the commits on your side or merged it after I squashed them.

I'm done here. If you want to move the extra paragraph to the other repo (which will still help people), you can do it.

2022-11-29 19:58 UTC, closed without merging